# Site settings
title: Dumpling
description: "Scriptable threaddump analyzer"
baseurl: "/dumpling"
url: "http://username.github.io/dumpling/"
github_repo: "dumpling"
github_username: olivergondza

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
